url: https://autonlab.github.io
baseurl: /30th-Anniversary

# Site settings
title: Auton Lab 30th Anniversary
email: ngisolfi@cs.cmu.edu  
description: "Auton Lab's 30th Anniversary"


# Team names, titles and social links
people:
- name: Artur Dubrawski
  pic: 4
  position: Research Professor, Director of the Auton Lab
  social:
    - url: https://web.archive.org/web/20031018171835/http://www.autonlab.org/autonweb/showPerson/28/

- name: Andrew Moore
  pic: 7
  position: Founder of the Auton Lab
  social:
    - url: https://web.archive.org/web/20010515234658/http://www.cs.cmu.edu/~awm/

- name: Barnabas Poczos
  pic: 5
  position: Associate Professor
  social:
    - title: homepage
      url: http://www.cs.cmu.edu/~bapoczos/

- name: Jeff Schneider
  pic: 6
  position: Research Professor
  social:
   - url: https://web.archive.org/web/20000824135211/http://www.cs.cmu.edu/~schneide/

  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/AutonLab
  - title: linkedin
    url: http://linkedin.com/company/cmu-auton-lab
  - title: github
    url: http://github.com/autonlab

# Postal address (add as many lines as necessary)
address:
  - line: 5000 Forbes Ave
  - line: Pittsburgh, PA 15213

# Build settings
markdown: kramdown
permalink: pretty
